//this is dummy data which was used before the backend was connected. This enabled us to test the functionality of the components during development.
const dummyData = [
  {
    id: 1,
    title: "Arrays",
    week: 1,
    day: 1,
    topicTitle: "Fundamentals of Javascript",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 1,
    title: "Arrays",
    week: 1,
    day: 1,
    topicTitle: "Fundamentals of Javascript",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 1,
    title: "Arrays",
    week: 1,
    day: 1,
    topicTitle: "Fundamentals of Javascript",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 2,
    title: "Variables",
    week: 1,
    day: 2,
    topicTitle: "Fundamentals of Javascript",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 3,
    title: "Components",
    week: 1,
    day: 3,
    topicTitle: "React",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 4,
    title: "Hooks",
    week: 2,
    day: 3,
    topicTitle: "React",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 5,
    title: "Props",
    week: 2,
    day: 2,
    topicTitle: "React",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
  {
    id: 6,
    title: "Functions",
    week: 2,
    day: 1,
    topicTitle: "Fundamentals of Javascript",
    complete: false,
    summary: "this is a summary",
    resources: ["resource 1", "resource 2"],
    notes: "",
    isChecked: false,
  },
];

export default dummyData;
